### ISSUE TITLE
bug under python 3.7.3

### ISSUE THREAD

**Issue by AndrewBoyHUN** [bczsalba/asztal#1]
Szia(sztok)!

Az alábbit kapom vissza telepítés és futtatás után:

[10:49:20]: Starting API
[10:49:20]: Maci acquired.
[10:49:20]: Getting marks...

Traceback (most recent call last):
  File "asztal.py", line 149, in <module>
    raise e
  File "asztal.py", line 135, in <module>
    err = user.start()
  File "/home/andrewboy/asztal/api.py", line 130, in start
    self.marks,self.subjectsList = self.getMarks()
  File "/home/andrewboy/asztal/api.py", line 160, in getMarks
    mk = json.loads(self.marksText)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
xxxx:/home/andrewboy/asztal# python3 --version
Python 3.7.3
xxxx:/home/andrewboy/asztal#

Azon gondolkodtam még, hogy ebből lehetne készíteni egy modult a magicmirror2-höz.

Ötlet esetleg, hogy a fenti mitől lehet?

köszi
üdv
A

**Comment by bczsalba** [comment]
Tudom nem ideális debug megoldás, de api.py 160. során egy print-tel meg lehetne nézni mi a self.marksText, mert elvileg ott a baj.

Nekem régebben csinált ilyeneket, de általában kitöröltem a marks.py file-t és másodjára lejött :D

**Comment by bczsalba** [comment]
Van valami frissites?

**Comment by svmorris** [comment]
lmao
